name: educase-assignment
services:
  school-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "4005:4005"
      - "4006:4006"
      - "28750:28750"
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run start"
